name: .NET Core CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

jobs:
  contract-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Setup Testcontainers Cloud Client
      uses: atomicjar/testcontainers-cloud-setup-action@v1
      with:
        token: ${{ secrets.TC_CLOUD_TOKEN }}
        wait: true

    - name: Run Tests with xUnit Output
      run: dotnet test --no-build --verbosity normal --logger "xunit;LogFileName=TestResults/test-result.xml" --results-directory ./TestResults 

    - name: Run Tests with xUnit Output
      run: dotnet test --no-build --verbosity normal --logger "xunit;LogFileName=test-result.xml" --results-directory ./TestResults 

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: TestResults/*/test-result.xml

    - name: Upload Test Results to GitHub Test Reporter
      uses: dorny/test-reporter@v1.9.1
      with:
        reporter: xunit
        name: Test Results
        path: TestResults/*/test-result.xml

    
    - name: Upload HTML Test Report
      uses: actions/upload-artifact@v4
      with:
        name: html-report
        path: specmatic-order-bff-csharp.test/build/reports/specmatic/html


    
